SHEET5
#+STARTUP: showall
#+SETUPFILE: options.org
#+OPTIONS: \n:nil

* TODO
  DEADLINE: <2009-11-25 Mer>

* Exercise 1
** (a) /getText/

#+BEGIN_SRC haskell 
getText :: IO String
getText = do
  x <- getChar
  if x == '\n'
     then
         return ""
     else do
         xs <- getText
         return (x:xs)
#+END_SRC
   
   
** (b) /getInt/
   
#+BEGIN_SRC haskell 
getInt :: IO Int
getInt = do
  n <- getText
  return (read n::Int)
#+END_SRC


** (c) /draw/
   
#+BEGIN_SRC haskell 
draw :: IO ()
draw = do
  putStr "Please enter a non-negative integer: "
  n <- getInt
  mapM_ (\_ ->putStrLn (concat $ replicate n "*")) [1..n]
  -- would be even better using replicateM_ from Control.monad
  -- replicateM_ n (\_ -> put ...)
#+END_SRC

* Exercise 2
  Given the following:

#+BEGIN_SRC haskell 
data MyMaybe a = Value a | Error

instance Monad MyMaybe where
    return = Value
    Error >>= q = Error
    Value x >>= q = q x
    
instance Show a => Show (MyMaybe a) where
    show Error = "an error occurred"
    show (Value x) = show x
#+END_SRC

** (a) Prove the three monad laws for it
   Before starting we number the three "rules" that we already have to be able to reference them later.

#+BEGIN_SRC haskell
   return = Value               (1)
   Error >>= q = Error          (2)
   Value x >>= q = q x          (3)
#+END_SRC

*** (1) p >>= return = p
    We have 2 cases:
    - (Value x) >>= return = return x (by 3)
      return x = Value x              (by 1)
    - Error >>= return = Error        (by 2)
    Hence, we show that the right neutrality is satisfied.

*** (2) return x >>= f = f x
    We have 2 cases:
     - return x = Value x    (by 1)
     - (Value x) >>= f = f x (by 3)
    Hence, we show that the left neutrality is satisfied.

*** (3) (p >>= \x -> q) >>= \y -> r = p >>= \x -> (q >>= \y -> r)
    
    Case p = Error
    For the LHS:
    - Error >>= \x -> q = Error (by 2)
    - Error >>= \y -> r = Error (by 2)
    For the RHS:
    - q >>= \y -> r = (Error || Value v)         (by 2 or 3)
    - Error >>= \x -> (Error || Value v) = Error (by 2)
    Hence, the LHS is equal to the RHS in producing Error.
    
    Case p = Value n
    For the LHS:
    - (Value n >>= \x -> q) = (Error || Value a)          (by 2 or 3)
    - (Error || Value a) >>= \y -> r = (Error || Value b) (by 2 or 3)
    For the RHS:
    - q >>= \y -> r = (Error || Value i) (by 2 or 3)
    - (Value n) >>= \x -> (Error || Value i) = (Error || Value i) (by 2 or 3)
    Hence, the LHS is equal to the RHS in producing either an Error or Value.
    
    Hence, we demonstrate that the associativity is satisfied.

** (b) Extend the data type Term with logarithm and let eval handle it

#+BEGIN_SRC haskell 
data Term = Con Float | Div Term Term | Log Term

eval :: Term -> MyMaybe Float
eval (Log x) = do
  y <- eval x
  if y <= 0 then Error else return $ log y

eval (Con x) = Value x
eval (Div t u) = do
  x <- eval t
  y <- eval u
  if y /= 0 then return (x/y) else Error
#+END_SRC


** (c) Replace MyMaybe with MyMaybe2 which must distinguish from the type of error and return a string
   
#+BEGIN_SRC haskell
data MyMaybe2 a = Value2 a | Error2 String

instance Monad MyMaybe2 where
    return = Value2
    Error2 x >>= q = Error2 x
    Value2 x >>= q = q x
    
instance Show a => Show (MyMaybe2 a) where
    show (Value2 x) = show x
    show (Error2 err) = err

eval2 :: Term -> MyMaybe2 Float
eval2 (Log x) = do
  y <- eval2 x
  if y <= 0
  then Error2 ("Cannot take logarithm of non-positive number " ++ show y ++ "!")
  else return $ log y

eval2 (Con x) = Value2 x
eval2 (Div t u) = do
  x <- eval2 t
  y <- eval2 u
  if y /= 0 then return (x/y) else Error2 "Cannot divide by zero!"
#+END_SRC
